<?php
    global $GOOGLEMAPS_PLUS_VC;
	global $VISUAL_COMPOSER_EXTENSIONS;
?>
<div id="ts-settings-language" class="tab-content">
    <div class="ts-vcsc-section-main">
		<div class="ts-vcsc-section-title ts-vcsc-section-show"><i class="dashicons-location-alt"></i>Google Maps (PLUS) Phrases</div>
		<div class="ts-vcsc-section-content slideFade">			
			<div class="ts-advanced-link-controls-wrapper" style="float: none; display: block; width: 100%; min-height: 40px; margin: 0; padding: 10px 0;">
				<div class="ts-advanced-link-button-wrapper ts-advanced-link-tooltip-holder" style="margin: 0 20px 0 0;">
					<span class="ts-advanced-link-tooltip-content"><?php echo __("Click here to restore all default text strings.", "ts_visual_composer_extend"); ?></span>
					<div id="ts-googlemapsvc-restore-button" class="ts-advanced-link-button-main ts-advanced-link-button-silver ts-advanced-link-button-default" style="margin: 0;">
						<?php echo __("Restore Defaults", "ts_visual_composer_extend"); ?>
					</div>
				</div>	
			</div>			
			<div class="ts-vcsc-notice-field ts-vcsc-success" style="margin-top: 10px; margin-bottom: 20px; font-size: 13px;">
			This plugin will store the language settings provided below with the same database option as our main Visual Composer add-on "<a href="http://codecanyon.net/item/visual-composer-extensions/7190695" target="_blank">Composium - Visual Composer Extensions</a>". By doing so, your language settings made via this plugin will automatically be available if you ever decide to switch to that other add-on, which also includes the Google Maps element from this add-on, and vice versa.
			</div>
		</div>
    </div>
    <div class="ts-vcsc-section-main">
		<div class="ts-vcsc-section-title ts-vcsc-section-show"><i class="dashicons-location-alt"></i>Google Maps (PLUS) Phrases</div>
		<div class="ts-vcsc-section-content slideFade">
			<div class="ts-vcsc-info-field ts-vcsc-warning" style="margin-top: 10px; margin-bottom: 20px; font-size: 13px;">
				The following text strings only apply to the new Google Maps PLUS element. The (old) "TS Google Maps (Deprecated)" element has its own translation options, shown further below on this page. When using the new Google Maps PLUS element, you will have the option to either use the global text strings you define above, or to define another set of custom text strings, using the inputs provided in the map settings panel itself.
			</div>
			<div class="ts-vcsc-notice-field ts-vcsc-warning" style="margin-top: 10px; margin-bottom: 20px; font-size: 13px;">General Text Strings</div>
			<div id="ts-googlemapsvc-translation-option" class="ts-googlemapsvc-translation-option">
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextListenersStart">"Start Listeners":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ListenersStart']; ?>" data-error="Text - Start Listeners" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextListenersStart" name="ts_vcsc_extend_settings_languageTextListenersStart" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ListenersStart']) ? $TS_VCSC_Google_MapPLUS_Language['ListenersStart'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ListenersStart']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ListenersStart'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ListenersStart'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextListenersStop">"Stop Listeners":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ListenersStop']; ?>" data-error="Text - Stop Listeners" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextListenersStop" name="ts_vcsc_extend_settings_languageTextListenersStop" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ListenersStop']) ? $TS_VCSC_Google_MapPLUS_Language['ListenersStop'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ListenersStop']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ListenersStop'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ListenersStop'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextMobileShow">"Show Google Map":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['MobileShow']; ?>" data-error="Text - Show Google Map" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextMobileShow" name="ts_vcsc_extend_settings_languageTextMobileShow" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['MobileShow']) ? $TS_VCSC_Google_MapPLUS_Language['MobileShow'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['MobileShow']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['MobileShow'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['MobileShow'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextMobileHide">"Hide Google Map":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['MobileHide']; ?>" data-error="Text - Hide Google Map" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextMobileHide" name="ts_vcsc_extend_settings_languageTextMobileHide" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['MobileHide']) ? $TS_VCSC_Google_MapPLUS_Language['MobileHide'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['MobileHide']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['MobileHide'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['MobileHide'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSelectLabel">"Zoom to Location":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SelectLabel']; ?>" data-error="Text - Zoom to Location" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSelectLabel" name="ts_vcsc_extend_settings_languageTextSelectLabel" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SelectLabel']) ? $TS_VCSC_Google_MapPLUS_Language['SelectLabel'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SelectLabel']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SelectLabel'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SelectLabel'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextControlsOSM">"Open Street":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsOSM']; ?>" data-error="Text - Open Street" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextControlsOSM" name="ts_vcsc_extend_settings_languageTextControlsOSM" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ControlsOSM']) ? $TS_VCSC_Google_MapPLUS_Language['ControlsOSM'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsOSM']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsOSM'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsOSM'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextControlsHome">"Home":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsHome']; ?>" data-error="Text - Home" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextControlsHome" name="ts_vcsc_extend_settings_languageTextControlsHome" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ControlsHome']) ? $TS_VCSC_Google_MapPLUS_Language['ControlsHome'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsHome']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsHome'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsHome'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextControlsBounds">"Fit All":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsBounds']; ?>" data-error="Text - Fit All" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextControlsBounds" name="ts_vcsc_extend_settings_languageTextControlsBounds" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ControlsBounds']) ? $TS_VCSC_Google_MapPLUS_Language['ControlsBounds'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsBounds']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsBounds'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsBounds'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextControlsBike">"Bicycle Trails":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsBike']; ?>" data-error="Text - Bicycle Trails" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextControlsBike" name="ts_vcsc_extend_settings_languageTextControlsBike" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ControlsBike']) ? $TS_VCSC_Google_MapPLUS_Language['ControlsBike'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsBike']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsBike'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsBike'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextControlsTraffic">"Traffic":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsTraffic']; ?>" data-error="Text - Traffic" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextControlsTraffic" name="ts_vcsc_extend_settings_languageTextControlsTraffic" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ControlsTraffic']) ? $TS_VCSC_Google_MapPLUS_Language['ControlsTraffic'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsTraffic']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsTraffic'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsTraffic'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextControlsTransit">"Transit":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsTransit']; ?>" data-error="Text - Transit" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextControlsTransit" name="ts_vcsc_extend_settings_languageTextControlsTransit" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ControlsTransit']) ? $TS_VCSC_Google_MapPLUS_Language['ControlsTransit'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsTransit']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ControlsTransit'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ControlsTransit'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextTrafficMiles">"Miles per Hour":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['TrafficMiles']; ?>" data-error="Text - Miles per Hour" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextTrafficMiles" name="ts_vcsc_extend_settings_languageTextTrafficMiles" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['TrafficMiles']) ? $TS_VCSC_Google_MapPLUS_Language['TrafficMiles'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['TrafficMiles']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['TrafficMiles'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['TrafficMiles'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextTrafficKilometer">"Kilometers per Hour":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['TrafficKilometer']; ?>" data-error="Text - Kilometers per Hour" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextTrafficKilometer" name="ts_vcsc_extend_settings_languageTextTrafficKilometer" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['TrafficKilometer']) ? $TS_VCSC_Google_MapPLUS_Language['TrafficKilometer'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['TrafficKilometer']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['TrafficKilometer'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['TrafficKilometer'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextTrafficNone">"No Data Available":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['TrafficNone']; ?>" data-error="Text - No Data Available" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextTrafficNone" name="ts_vcsc_extend_settings_languageTextTrafficNone" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['TrafficNone']) ? $TS_VCSC_Google_MapPLUS_Language['TrafficNone'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['TrafficNone']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['TrafficNone'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['TrafficNone'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSearchGoogle">"View on Google Maps":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchGoogle']; ?>" data-error="Text - View on Google Maps" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSearchGoogle" name="ts_vcsc_extend_settings_languageTextSearchGoogle" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SearchGoogle']) ? $TS_VCSC_Google_MapPLUS_Language['SearchGoogle'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchGoogle']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchGoogle'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchGoogle'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSearchDirections">"Get Directions":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchDirections']; ?>" data-error="Text - Get Directions" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSearchDirections" name="ts_vcsc_extend_settings_languageTextSearchDirections" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SearchDirections']) ? $TS_VCSC_Google_MapPLUS_Language['SearchDirections'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchDirections']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchDirections'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchDirections'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextOtherLink">"Learn More!":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['OtherLink']; ?>" data-error="Text - Learn More!" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextOtherLink" name="ts_vcsc_extend_settings_languageTextOtherLink" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['OtherLink']) ? $TS_VCSC_Google_MapPLUS_Language['OtherLink'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['OtherLink']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['OtherLink'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['OtherLink'])); ?>" size="100">
				</div>
				<div class="ts-vcsc-notice-field ts-vcsc-warning" style="margin-top: 10px; margin-bottom: 20px; font-size: 13px;">New Address Search Feature</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSearchButton">"Find New Location":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchButton']; ?>" data-error="Text - Find New Location" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSearchButton" name="ts_vcsc_extend_settings_languageTextSearchButton" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SearchButton']) ? $TS_VCSC_Google_MapPLUS_Language['SearchButton'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchButton']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchButton'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchButton'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSearchHolder">"Enter address to search for ...":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchHolder']; ?>" data-error="Text - Enter address to search for ..." data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSearchHolder" name="ts_vcsc_extend_settings_languageTextSearchHolder" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SearchHolder']) ? $TS_VCSC_Google_MapPLUS_Language['SearchHolder'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchHolder']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchHolder'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchHolder'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSearchGroup">"Map Search":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchGroup']; ?>" data-error="Text - Map Search" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSearchGroup" name="ts_vcsc_extend_settings_languageTextSearchGroup" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SearchGroup']) ? $TS_VCSC_Google_MapPLUS_Language['SearchGroup'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchGroup']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SearchGroup'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SearchGroup'])); ?>" size="100">
				</div>	
				<div class="ts-vcsc-notice-field ts-vcsc-warning" style="margin-top: 10px; margin-bottom: 20px; font-size: 13px;">Text Strings Used in Select Boxes</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextStyleDefault">"Google Standard":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['StyleDefault']; ?>" data-error="Text - Google Standard" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextStyleDefault" name="ts_vcsc_extend_settings_languageTextStyleDefault" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['StyleDefault']) ? $TS_VCSC_Google_MapPLUS_Language['StyleDefault'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['StyleDefault']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['StyleDefault'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['StyleDefault'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextStyleLabel">"Change Map Style":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['StyleLabel']; ?>" data-error="Text - Change Map Style" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextStyleLabel" name="ts_vcsc_extend_settings_languageTextStyleLabel" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['StyleLabel']) ? $TS_VCSC_Google_MapPLUS_Language['StyleLabel'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['StyleLabel']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['StyleLabel'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['StyleLabel'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextFilterAll">"All Groups":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['FilterAll']; ?>" data-error="Text - All Groups" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextFilterAll" name="ts_vcsc_extend_settings_languageTextFilterAll" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['FilterAll']) ? $TS_VCSC_Google_MapPLUS_Language['FilterAll'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['FilterAll']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['FilterAll'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['FilterAll'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextFilterLabel">"Filter by Groups":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['FilterLabel']; ?>" data-error="Text - Filter by Groups" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextFilterLabel" name="ts_vcsc_extend_settings_languageTextFilterLabel" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['FilterLabel']) ? $TS_VCSC_Google_MapPLUS_Language['FilterLabel'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['FilterLabel']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['FilterLabel'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['FilterLabel'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSumoConfirm">"Confirm":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoConfirm']; ?>" data-error="Text - Confirm" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSumoConfirm" name="ts_vcsc_extend_settings_languageTextSumoConfirm" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SumoConfirm']) ? $TS_VCSC_Google_MapPLUS_Language['SumoConfirm'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoConfirm']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoConfirm'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoConfirm'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSumoCancel">"Cancel":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoCancel']; ?>" data-error="Text - Cancel" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSumoCancel" name="ts_vcsc_extend_settings_languageTextSumoCancel" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SumoCancel']) ? $TS_VCSC_Google_MapPLUS_Language['SumoCancel'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoCancel']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoCancel'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoCancel'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSumoSelected">"Selected":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoSelected']; ?>" data-error="Text - Selected" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSumoSelected" name="ts_vcsc_extend_settings_languageTextSumoSelected" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SumoSelected']) ? $TS_VCSC_Google_MapPLUS_Language['SumoSelected'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoSelected']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoSelected'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoSelected'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSumoAllSelected">"All Selected":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoAllSelected']; ?>" data-error="Text - All Selected" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSumoAllSelected" name="ts_vcsc_extend_settings_languageTextSumoAllSelected" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SumoAllSelected']) ? $TS_VCSC_Google_MapPLUS_Language['SumoAllSelected'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoAllSelected']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoAllSelected'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoAllSelected'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSumoPlaceholder">"Select Here":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoPlaceholder']; ?>" data-error="Text - Select Here" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSumoPlaceholder" name="ts_vcsc_extend_settings_languageTextSumoPlaceholder" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SumoPlaceholder']) ? $TS_VCSC_Google_MapPLUS_Language['SumoPlaceholder'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoPlaceholder']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoPlaceholder'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoPlaceholder'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextPlaceholderMarker">"Select Location":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['PlaceholderMarker']; ?>" data-error="Text - Select Location" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextPlaceholderMarker" name="ts_vcsc_extend_settings_languageTextPlaceholderMarker" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['PlaceholderMarker']) ? $TS_VCSC_Google_MapPLUS_Language['PlaceholderMarker'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['PlaceholderMarker']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['PlaceholderMarker'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['PlaceholderMarker'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSumoSearchLocations">"Search Locations":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoSearchLocations']; ?>" data-error="Text - Search Locations" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSumoSearchLocations" name="ts_vcsc_extend_settings_languageTextSumoSearchLocations" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SumoSearchLocations']) ? $TS_VCSC_Google_MapPLUS_Language['SumoSearchLocations'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoSearchLocations']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoSearchLocations'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoSearchLocations'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSumoSearchGroups">"Search Groups":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoSearchGroups']; ?>" data-error="Text - Search Groups" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSumoSearchGroups" name="ts_vcsc_extend_settings_languageTextSumoSearchGroups" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SumoSearchGroups']) ? $TS_VCSC_Google_MapPLUS_Language['SumoSearchGroups'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoSearchGroups']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoSearchGroups'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoSearchGroups'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextSumoSearchStyles">"Search Styles":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoSearchStyles']; ?>" data-error="Text - Search Styles" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextSumoSearchStyles" name="ts_vcsc_extend_settings_languageTextSumoSearchStyles" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['SumoSearchStyles']) ? $TS_VCSC_Google_MapPLUS_Language['SumoSearchStyles'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoSearchStyles']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['SumoSearchStyles'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['SumoSearchStyles'])); ?>" size="100">
				</div>
				<div class="ts-vcsc-notice-field ts-vcsc-warning" style="margin-top: 10px; margin-bottom: 20px; font-size: 13px;">Detailed Location Listing Below Map</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextListingsButton">"Search Locations":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ListingsButton']; ?>" data-error="Text - Search Locations" data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextListingsButton" name="ts_vcsc_extend_settings_languageTextListingsButton" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ListingsButton']) ? $TS_VCSC_Google_MapPLUS_Language['ListingsButton'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ListingsButton']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ListingsButton'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ListingsButton'])); ?>" size="100">
				</div>
				<div style="margin: 10px auto;">
					<label class="Uniform" style="display: inline-block;" for="ts_vcsc_extend_settings_languageTextListingsSearch">"Enter location to search for ...":</label>
					<input class="validate[required]" data-default="<?php echo $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ListingsSearch']; ?>" data-error="Text - Enter location to search for ..." data-order="2" type="text" style="width: 20%;" id="ts_vcsc_extend_settings_languageTextListingsSearch" name="ts_vcsc_extend_settings_languageTextListingsSearch" value="<?php echo (isset($TS_VCSC_Google_MapPLUS_Language['ListingsSearch']) ? $TS_VCSC_Google_MapPLUS_Language['ListingsSearch'] : (isset($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ListingsSearch']) ? $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_Google_MapPLUS_Language_Defaults['ListingsSearch'] : $GOOGLEMAPS_PLUS_VC->TS_GMVC_Google_MapPLUS_Language_Defaults['ListingsSearch'])); ?>" size="100">
				</div>
			</div>
		</div>
    </div>
</div>